spring:
  application:
    name: security-example-demo
  datasource:
    name: zebra
    url: jdbc:mysql://localhost:3306/kaka-example?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  session:
    store-type: none
server:
  port: 8080