spring:
  application:
    name: security-example-demo
  datasource:
    name: zebra
    url: jdbc:mysql://localhost:3306/security-example?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  session:
    store-type: none
  redis:
    cluster:
      nodes: 172.16.12.3:7000,172.16.12.3:7001,172.16.12.3:7002,172.16.12.3:7003,172.16.12.3:7004,172.16.12.3:7005
    timeout: 10000
    password:
    database: 0
    jedis:
          pool:
            # 连接池最大阻塞等待时间(使用负值表示没有限制)
            max-wait: -1
            # 连接池最大连接数(使用负值表示没有限制)
            max-active: 8
            # 连接池中的最大空闲连接
            max-idle: 8
            # 连接池中的最小空闲连接
            min-idle: 0

server:
  port: 80
core:
  security:
    browser:
#      loginPage: /myLogin.html
      loginResponseType: JSON
    code:
      imageCode:
        codeCount: 4
#        urls: /user/**,/test/*
    social:
      filterProcessesUrl: /qqLogin
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
